# Generated by Django 5.2.9 on 2026-05-22 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_filerecord_deleted_at_filerecord_is_latest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('title_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='source_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='layout',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='platform',
            field=models.CharField(choices=[('ga4', 'Google Analytics 4'), ('gsc', 'Google Search Console'), ('gmb', 'Google My Business'), ('ahrefs', 'Ahrefs'), ('semrush', 'SEMrush'), ('figma', 'Figma')], max_length=20),
        ),
    ]
