# Generated by Django 6.0 on 2025-12-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission_remove_user_role_user_category_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_working_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
    ]
