# Generated by Django 6.0 on 2026-05-23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_daily_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code_hash', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to='authentication.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
